-- Seed reference lists (generated). Idempotent: skips duplicates.
INSERT INTO dog_breeds (name, sort_order)
SELECT name, sort_order FROM (VALUES
('Abyssinian', 0),
('Affenpinscher', 1),
('Africanis', 2),
('African Mau', 3),
('Airedale', 4),
('Airedale Terrier', 5),
('Akbash Dog', 6),
('Akita', 7),
('Alabai', 8),
('Alapha Blue Blood Bulldog', 9),
('Alaskan Husky', 10),
('Alaskan Klee Kai', 11),
('Alaskan Malamute', 12),
('American Akita', 13),
('American Bobtail', 14),
('American Bulldog', 15),
('American Bully', 16),
('American Cocker Spaniel', 17),
('American Curl', 18),
('American Eskimo', 19),
('American Foxhound', 20),
('American Shorthair', 21),
('American Staffordshire Terrier', 22),
('American Water Spaniel', 23),
('American Wirehair', 24),
('Amstaff', 25),
('Anatolian Shepherd', 26),
('Angolan Stray', 27),
('Angora', 28),
('Appenzeller', 29),
('Arabian Mau', 30),
('Australian Cattle Dog', 31),
('Australian Cobber Dog', 32),
('Australian Kelpie', 33),
('Australian Shepherd', 34),
('Australian Silky Terrier', 35),
('Australian Terrier', 36),
('Autrailan Labradoodle', 37),
('azawakh', 38),
('Balinese', 39),
('Balonka', 40),
('Basenji', 41),
('Basset Hound', 42),
('Beagle', 43),
('Beagle Mix', 44),
('Beagle/Terrier Cross', 45),
('Beauceron', 46),
('BEAUCERON', 47),
('Bedlington Terrier', 48),
('Belgian Malinois', 49),
('Belgian Sheepdog', 50),
('Belgian Shepherd', 51),
('Belgian Tervuren', 52),
('Bengal', 53),
('Bernedoodle', 54),
('Bernese Mountain Dog', 55),
('Bichon Frise', 56),
('biewer yorkie', 57),
('Birman', 58),
('Bichon x Maltese', 59),
('Black and Tan Coonhound', 60),
('Black Mouth Cur', 61),
('Black Russian Terrier', 62),
('Bluetick coonhound', 63),
('bolognese', 64),
('Bombay', 65),
('Boomer', 66),
('Border Collie', 67),
('Border Collie Mix', 68),
('Border Terrier', 69),
('Borzoi', 70),
('Boseagle', 71),
('Boston Terrier', 72),
('Bouvier des Flandres', 73),
('Boxer', 74),
('Boxer Mix', 75),
('Boykin Spaniel', 76),
('Briard', 77),
('Briquet Griffon Vendeen', 78),
('British', 79),
('British Blue', 80),
('British Longhair Kitten', 81),
('British Shorthair', 82),
('Brittany', 83),
('Brussels Griffon', 84),
('Bulldog', 85),
('Bulldog x Pug', 86),
('Bullmastiff', 87),
('Bull Terrier', 88),
('Burmese', 89),
('Cairn Terrier', 90),
('Canaan Dog', 91),
('Cane Corso', 92),
('Cardigan Welsh Corgi', 93),
('Catahoula Leopard Dog', 94),
('Cavachon', 95),
('Cavador', 96),
('Cavalier', 97),
('Cavalier King Charles Spaniel', 98),
('Cavapoo', 99),
('Central Asian Ovtcharka', 100),
('Cesky Terrier', 101),
('Chartreux', 102),
('Chesapeake Bay Retriever', 103),
('Chihuahua', 104),
('Chihuahua cross', 105),
('Chihuahua cross Terrier', 106),
('Chihuahua/Jack Russel', 107),
('chihuahua mix', 108),
('Chihuahua/Retriever', 109),
('Chihuahua/West Highland Terrier', 110),
('Chihuau', 111),
('Chinese Crested', 112),
('Chow Chow', 113),
('Chow Chow Mix', 114),
('Chow/labrador', 115),
('CIRNECO DELL''ETNA', 116),
('Clumber Spaniel', 117),
('Cockador', 118),
('Cocker Spaniel', 119),
('Cocker Spaniel Mixed', 120),
('Cocker Spaniel x Cavalier', 121),
('Cocker Zhu', 122),
('Collie', 123),
('Collie Miexed', 124),
('Colorpoint Shorthair', 125),
('Coonhound', 126),
('Corgi', 127),
('Corgi Splitz Mix', 128),
('Cornish Rex', 129),
('Coton De Tulear', 130),
('Cross', 131),
('Cross Pug/Bulldog', 132),
('Czech Wolfdog', 133),
('Dachshund', 134),
('Dachshund x Jack Russel x Flat', 135),
('Dachsund Cross', 136),
('Dalmatian', 137),
('Dandie Dinmont Terrier', 138),
('Danish-Swedish Farmdog', 139),
('Desert Dog', 140),
('Desert Mix', 141),
('Devon Rex', 142),
('Doberman Pinscher', 143),
('Dogue de Bordeaux', 144),
('Domestic Cat', 145),
('Domestic Long Hair', 146),
('Domestic Short Hair', 147),
('Dubai Special', 148),
('Dubai partridge', 149),
('Dutch partridge', 150),
('Dutch Shepherd', 151),
('Egyptian Mau', 152),
('English bulldog', 153),
('English bulldog /mops', 154),
('English Cocker Spaniel', 155),
('English Foxhound', 156),
('English Pointer', 157),
('English Setter', 158),
('English Shepherd', 159),
('English Springer Spaniel', 160),
('English Toy Spaniel', 161),
('Estrela Mountain Dog', 162),
('European Burmese', 163),
('European short hair', 164),
('Exotic', 165),
('Field Spaniel', 166),
('Fila Brasileiro', 167),
('Finnish Lapphund', 168),
('Finnish Spitz', 169),
('Flat-Coated Retriever', 170),
('Fox Terrier (Smooth)', 171),
('Fox Terrier (Wire)', 172),
('Frenchie', 173),
('French Bulldog', 174),
('French Bulldog cross', 175),
('German Pincher', 176),
('German Shepherd', 177),
('German Shepherd Cross', 178),
('German Shepherd cross Rottweiler', 179),
('German Shepherd Dog', 180),
('German Shepherd Mix', 181),
('German Shepherd Pitbull Mix', 182),
('German Shepherd X Chow Chow', 183),
('German Shepherd x Husky', 184),
('German Shorthaired Pointer', 185),
('German Spitz', 186),
('German Spitz/Pomeranian', 187),
('German Wirehaired Pointer', 188),
('Giant Schnauzer', 189),
('Goberian', 190),
('Goldendoodle', 191),
('Golden Doodle', 192),
('Golden Retriever', 193),
('Golden Retriever Mixed', 194),
('Golden Retriever x Cocker Spaniel', 195),
('Golden Shepherd', 196),
('Gordon Setter', 197),
('Great Bernese', 198),
('Great Dane', 199),
('Great Dane/ Australian cattle', 200),
('Great Dane Mixed', 201),
('Greater Swiss Mountain Dog', 202),
('Great Pyrenees', 203),
('Greyhound', 204),
('Griffon', 205),
('GSD mix', 206),
('GSD / Saluki', 207),
('Harrier', 208),
('Harrier Cross Jindo', 209),
('Hat Coated Retriever', 210),
('Havanese', 211),
('havanese mix', 212),
('Havanese x Maltese', 213),
('Himalayan Persian', 214),
('Hovawart', 215),
('Hungarian Vizsla', 216),
('Husky', 217),
('Husky german sheperd', 218),
('husky mix', 219),
('Husky x Saluki', 220),
('Ibizan Hound', 221),
('Indian Pariah', 222),
('Irish Setter', 223),
('Irish Soft Coated', 224),
('Irish Terrier', 225),
('Irish Water Spaniel', 226),
('Irish Wolfhound', 227),
('Italian Greyhound', 228),
('Italian Spinone', 229),
('Italian Waterdog', 230),
('Jack', 231),
('Jackapoo', 232),
('Jack Cross', 233),
('jack russell/chihuahua', 234),
('Jack russell / daxi', 235),
('Jack Russell', 236),
('Jack Russell Terrier', 237),
('Jack Russel Mix', 238),
('jackrussel /poodle', 239),
('Japanese Bobtail', 240),
('Japanese Chin', 241),
('Japanese Spitz', 242),
('Javanese', 243),
('Jindo', 244),
('Jinmu Husky', 245),
('Keeshond', 246),
('Kelpie x Red Heeler', 247),
('Kerry Blue Terrier', 248),
('King Charles', 249),
('Kokoni Cross', 250),
('Komondor', 251),
('Kooikerhondje', 252),
('Korat', 253),
('Kavasz', 254),
('Labradoodle', 255),
('Labrador', 256),
('Labrador Crossed', 257),
('Labradorhound', 258),
('Labrador Mixed', 259),
('Labrador Retriever', 260),
('labrador-sheppared cross', 261),
('Lagotto', 262),
('Lakeland Terrier', 263),
('LaPerm', 264),
('Leonberger', 265),
('lhasa apso', 266),
('Lhasa Apso', 267),
('Local Mixed', 268),
('Lowchen', 269),
('Lurcher', 270),
('Magyar Vizsla', 271),
('Maine Coon', 272),
('Malamute', 273),
('Malamute/Husky', 274),
('Malinois Mix', 275),
('Maltese', 276),
('maltese havanese', 277),
('Maltese Mix', 278),
('Maltese Terrier', 279),
('Maltese x Poodle', 280),
('Maltichon', 281),
('Maltipoo', 282),
('Manchester Terrier', 283),
('Manx', 284),
('Maremmano-Abruzzese Sheepdog', 285),
('maremma/retriever', 286),
('Maremma Sheepdog', 287),
('Mau', 288),
('Miniature Australian Shepherd', 289),
('Miniature Bull Terrier', 290),
('Miniature Dachshund', 291),
('Miniature Labradoodle', 292),
('Miniature Pinscher', 293),
('Miniature Pinscher Cross', 294),
('Miniature Pinscher/Miniature', 295),
('Miniature Poodle', 296),
('Miniature Schnauzer', 297),
('Mini Daxie', 298),
('Mini Maltese', 299),
('Mini Pomeranian', 300),
('Mixed', 301),
('Mixed Breed', 302),
('mixed shih', 303),
('Mixed Terrier', 304),
('Mix Pointer', 305),
('Mix Spaniel', 306),
('Mountain Cur', 307),
('Mutt', 308),
('My Breed is not listed', 309),
('NewF. cross', 310),
('Newfoundland', 311),
('Northern Inuit', 312),
('Norwegian Buhund', 313),
('Norwegian Elkhound', 314),
('Norwegian Forest Cat', 315),
('Norwich Terrier', 316),
('Nova Scotia Duck Tolling Retriever', 317),
('Old English Sheepdog', 318),
('Oriental', 319),
('Otterhound', 320),
('Papillon', 321),
('Papillon x Spitz', 322),
('patterdale terrier', 323),
('Patter Jack Crossed Breed', 324),
('Pekinese/Pomeranian', 325),
('Pekingese', 326),
('Pekingese Cross', 327),
('Pekingese/Chihuahua', 328),
('Pembroke Welsh Corgi', 329),
('Persian', 330),
('Petit Basset Griffon Vendeen', 331),
('Petit Brabancon', 332),
('Pharaoh Hound', 333),
('Phu Quoc', 334),
('Pitbull', 335),
('Pitbull/Border Collie', 336),
('Pitbull Terrier X', 337),
('Pit mix', 338),
('Pocket Bully', 339),
('Pointer', 340),
('Polish Owczarek Nizinny', 341),
('Pomchi', 342),
('Pomeranian', 343),
('pomeranian chihuahua', 344),
('Pomeranian cross', 345),
('Pomeranian/Terrier Mix', 346),
('Pomeranian Toy', 347),
('Pomeranian x Papillon', 348),
('Pomeranian x Poodle', 349),
('Pomsky', 350),
('Pomsky Mix', 351),
('Pom x Spitz', 352),
('Poochon', 353),
('Poodle', 354),
('Poodle Mix', 355),
('Poodle - Standard', 356),
('Portuguese Podengo', 357),
('Portuguese Water Dog', 358),
('Prague Ratter', 359),
('Puggle', 360),
('Pug Mix', 361),
('Pug x Chihuahua', 362),
('Pug x Shih Tzu', 363),
('Puli', 364),
('RagaMuffin', 365),
('Ragdoll', 366),
('Rat Terrier', 367),
('Red and White Setter', 368),
('Redbone Coonhound', 369),
('Rescue Dog', 370),
('Retriever X', 371),
('Rhodesian Ridgeback', 372),
('Rhodesian Ridgeback X Labrador', 373),
('Rottie X Great Dane', 374),
('Rottweiler', 375),
('Rottweiler x German Shepherd', 376),
('Rough Collie', 377),
('Russian Blue', 378),
('Russian Toy Terrier', 379),
('Saint Bernard', 380),
('saluki', 381),
('saluki cannan', 382),
('Saluki Cross', 383),
('Saluki/Jack Russel', 384),
('saluki lurcher', 385),
('Saluki Mix', 386),
('Saluki x Labrador', 387),
('Samoyed', 388),
('Schipperke', 389),
('Schnauzer', 390),
('Snoozle', 391),
('Scottish Deerhound', 392),
('Scottish Fold', 393),
('Scottish Straight', 394),
('Scottish Setter', 395),
('Scottish Terrier', 396),
('Sealyham Terrier', 397),
('Selkirk Rex', 398),
('Shar-Pei', 399),
('Sheep Dog', 400),
('Sheepo', 401),
('Shepard mix', 402),
('Shepsky', 403),
('Shetland Sheepdog', 404),
('Shiba-Inu', 405),
('Shiba Inu x Border Collie', 406),
('Shiba Inu X Pomeranian', 407),
('Shiba + Jack Russel', 408),
('Shiba x Pomeranian', 409),
('Shibu Inu Cross', 410),
('Shih Tzu', 411),
('Silky Terrier', 412),
('Singapura', 413),
('Skye Terrier', 414),
('Somali', 415),
('South African GreyHound', 416),
('Spaniel', 417),
('Spaniel/daschund', 418),
('Spaniel/Terrier Mix', 419),
('Spanish Podenco', 420),
('Spanish Water dog', 421),
('Sphynx', 422),
('Spinone Italiano', 423),
('Spitz Cross', 424),
('Spitz x Dachshund', 425),
('Springer Spaniel', 426),
('Spritz Terrier', 427),
('Sprocker Spaniel', 428),
('Staffie', 429),
('Staffordshire Bull Terrier', 430),
('Staff x Lab', 431),
('Standard Daschund', 432),
('Standard Poodle', 433),
('Standard Schnauzer', 434),
('Street', 435),
('Sussex Spaniel', 436),
('Swiss Shepherd', 437),
('Tabby', 438),
('TeaCup', 439),
('Teddybear', 440),
('Terrier', 441),
('terrier/border collie', 442),
('Terrier Mix', 443),
('Tibetan Mastiff', 444),
('Tibetan Spaniel', 445),
('Tibetan Terrier', 446),
('Tonkinese', 447),
('Toy Manchester Terrier', 448),
('Toy Poodle', 449),
('Turkish Angora', 450),
('Turkish Cross', 451),
('Turkish Van', 452),
('Turtle', 453),
('Vizsla', 454),
('Weimaraner', 455),
('Welsh Springer Spaniel', 456),
('Welsh Terrier', 457),
('West Highland Cross', 458),
('West Highland White Terrier', 459),
('westie', 460),
('Westie x Poodle', 461),
('wheaten terrier', 462),
('Whippet', 463),
('Whippet Terrier', 464),
('Whippet x Labrador', 465),
('White Shepherd', 466),
('Wire Fox Terrier', 467),
('Wirehaired Pointing Griffon', 468),
('Wolf', 469),
('Xoloitzcuintli', 470),
('Yorkie', 471),
('Yorkie Cross', 472),
('Yorkie/Poodle', 473),
('YorkiexRetriever', 474),
('york shire', 475),
('Yorkshire Terrier', 476)
) AS v(name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM dog_breeds d WHERE d.name = v.name);

INSERT INTO vet_clinics (name)
SELECT v.name FROM (VALUES
('Advanced Pet Clinic'),
('Al Barsha'),
('AL Canary Veterinary Clinic'),
('Al Falah Veterinary Clinic'),
('Al Jawareh Vet Clinic'),
('Al Maha Vet Clinic'),
('Al Nawadir Vet LLC'),
('AL Oropi Veterinary Clinic Sharjah'),
('Al Qouz Vet Hospital'),
('AL RAHA VET CLINIC'),
('Al Rayan Vet Clinic'),
('Al Safa Veterinary Clinic'),
('Al Tareeq Vet Clinic'),
('American Veterinary Clinic'),
('Amity Veterinary Clinic'),
('Amore Vet Clinic'),
('Animal Planet Clinic'),
('Animal Recovery Veterinary Referral'),
('Animal Specialist Clinic'),
('Anubis Vet Clinic'),
('Arabian Ranches Polo Club'),
('Australian Veterinary Clinic'),
('Australian Veterinary Hospital'),
('Axiom Vet Lab Ltd'),
('Blue Oasis Veterinary Clinic'),
('British Veterinary Centre'),
('British Veterinary Hospital'),
('BVC Clinic'),
('Canadian Veterinary Clinic'),
('Cardio Vet Veterinary Clinic'),
('City Vet Clinic'),
('Cloud 9'),
('Craighall Vet Hosp CNR Buckingham'),
('Creekside Vet Clinic'),
('Culverden Vet Group'),
('Deira Vet Clinic'),
('DKC Veterinary Clinic'),
('Dodteur Venerinaire'),
('Dog Venturez Vet Clinic'),
('Dolphin Veterinary Clinic'),
('Dreamers Vet Clinic'),
('Dreamers Veterinary Clinic LLC'),
('Dr. Elizabeth'),
('Dr. Paulina Vet Care Polo Club'),
('Dr Rami Mdawar Vet'),
('Dr. Reza Sadeghi'),
('Dr. Samir Vet Clinic'),
('Dr. Well Vet Clinic'),
('Dubai Hills Vet'),
('Dubai Municipality Veterinary Clinic'),
('Dubai Veterinary Hospital'),
('Emirates Veterinary Clinic/Center'),
('Energetic Panacea Veterinary Clinic'),
('European Veterinary Center'),
('EuroPet Sharjah'),
('Europets Veterinary Hospital'),
('Falcon Hospital Abu Dhabi'),
('German Veterinary Clinic'),
('Harmony Vet Clinic'),
('Hills Vet'),
('Hub Pet Clinic'),
('International Veterinary Hospital'),
('Intervet Vet Clinic'),
('Jet Pets Animal Transport'),
('Karas Vet Clinic'),
('Kare Vet Clinic'),
('Little Hearts Veterinary Clinic'),
('Lucky Veterinary Clinic'),
('Magdalena Vet'),
('Matts Veterinary Clinic'),
('Mike''s Vet'),
('Modern Veterinary Clinic'),
('My Second Home Dubai'),
('My Vet is not listed'),
('N/A'),
('Nad Al Shiba Veterinary Hospital'),
('Noble Veterinary Clinic'),
('Ohmer Kabbi Vet'),
('Orthopedic Veterinary Clinic LLC'),
('PANACEA'),
('Pawsitive Vet'),
('Pawsome Place'),
('Perfect Dose Veterinary'),
('Pet Board'),
('Pet Bond'),
('Petbook Veterinary Clinic'),
('Pet Connection Veterinary Clinic'),
('Pet First Veterinary Clinic'),
('PET FRIENDS VET CLINIC'),
('Pet Land Veterinary Clinic'),
('Pet Lovers Veterinary Clinic'),
('Petology'),
('Pet Point'),
('Pet Pulse Vet'),
('Pets Avenue'),
('Pets Health'),
('Pets Heaven Veterinary Clinic'),
('Pets Society'),
('Pets Station'),
('Pets & Us Veterinary Clinic'),
('Petzone Veterinary Clinic'),
('Provet Clinic'),
('QV Lucinda'),
('Rak Animal Welfare Centre Fze'),
('Royal Vet Clinic'),
('Royal Veterinary Center'),
('RUSTY VETERINARY CLINIC'),
('SABB'),
('Salamak Veterinary Clinic'),
('SAMIR VET CLINIC'),
('SAVET TERRITORY VET CLINIC'),
('South Boston'),
('Star Vet Clinic'),
('The Cat Vet'),
('The City Vet Clinic'),
('The Equine and Small Animal Surgery'),
('The Hills Veterinary Clinic'),
('The Pet House Vet Clinic'),
('The Veterinary Hospital'),
('TWEED HOUSE VETERINARY SURGERY'),
('Two Feet Four Paws Veterinary Clinic'),
('Umm Sequiem Vet Clinic'),
('Umm Suqeim Veterinary Clinic'),
('UNKNOWN'),
('US Vet Center'),
('VACCICHECK DONE AT JVC EXP'),
('VCT Veterinary Clinic'),
('Vetcare Veterinary Medical Centre'),
('Vet Dub FZ LLC'),
('VETERNINARY CLINIC LLC'),
('Vet Plus'),
('Vet Plus Dubai'),
('Vets24 Vet Clinic LLC'),
('Vets For Pets Veterinary Clinic'),
('Vets & Pets'),
('Vienna Veterinary Clinic'),
('Whiskers & Wags Veterinary Clinic'),
('Zabeel Veterinary Hospital Dubai', 137)
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM vet_clinics c WHERE c.name = v.name);
